### ISSUE TITLE
 can't have empty dictionary (put a word in to test, deleted it to clear)

### ISSUE THREAD

**Issue by AnKingMed** [AnKing-VIP/spell-checker-addon#7]
Caught exception:
Traceback (most recent call last):
  File "/Users/Nick/Library/Application Support/Anki2/addons21/1410276506/dict.py", line 209, in apply
    content = create_bdic(words, aff)
  File "/Users/Nick/Library/Application Support/Anki2/addons21/1410276506/bdicwriter/__init__.py", line 95, in create_bdic
    dic_bytes(words, output)
  File "/Users/Nick/Library/Application Support/Anki2/addons21/1410276506/bdicwriter/__init__.py", line 72, in dic_bytes
    trie_root.build(bytewords, 0, len(bytewords), 0)
  File "/Users/Nick/Library/Application Support/Anki2/addons21/1410276506/bdicwriter/dic.py", line 62, in build
    begin_str = words[begin]
IndexError: list index out of range

**Comment by BlueGreenMagick** [comment]
Fixed!
